name: Check PHP syntax

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
      # Install PHP interpreter
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # Checkout source repository
      - name: checkout repo
        uses: actions/checkout@v3

      # Lint every PHP source file using PHP interpreter
      - name: Check PHP syntax
        run: composer run check-syntax

      - name: composer install
        if: ${{ matrix.php-version == '8.3' }}
        run: composer install --no-progress

      - name: PHPCodeSniffer
        if: ${{ matrix.php-version == '8.3' }}
        run: ./vendor/bin/phpcs -s
